# Comparing instrument mm's

In [1]:
import instrument_mm
from pyMuellerMat import common_mms as cmm
import numpy as np

# Example parameter values for testing
instrument_mm.compare_mueller_matrices(
    delta_m3=0.25, epsilon_m3=0.05, offset_m3=5,
    delta_HWP=0.5, offset_HWP=10, delta_derot=0.3,
    offset_derot=5, delta_opts=0.1, epsilon_opts=0.03,
    rot_opts=15, delta_FLC=0.25, rot_FLC=30,
    em_gain=1.0, parang=45, altitude=30,
    HWP_ang=22.5, IMR_ang=45, cam_num=1, FLC_state=1
)


Instrumental Mueller Matrix (Original):
[[ 0.51291142  0.00574749  0.15364932 -0.48932298]
 [ 0.51291142  0.00574749  0.15364932 -0.48932298]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]

Instrumental Mueller Matrix (Updated):
[[ 0.51291142  0.00574749  0.15364932 -0.48932298]
 [ 0.51291142  0.00574749  0.15364932 -0.48932298]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]

Difference between the matrices:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Comparing Internal Calibration Outputs

In [2]:
# Example system dictionary with tags for internal calibration
system_dict = {
    "components": {
        "parang_rot": {
            "type": "Rotator",
            "properties": {"pa": 45},
            "tag": "on-sky",
        },
        "m3": {
            "type": "DiattenuatorRetarder",
            "properties": {"phi": 2 * np.pi * 0.25, "epsilon": 0.05},
            "tag": "on-sky",
        },
        "alt_rot": {
            "type": "Rotator",
            "properties": {"pa": -30},
            "tag": "internal",
        },
        "hwp": {
            "type": "Retarder",
            "properties": {"phi": 2 * np.pi * 0.5, "theta": 0},
            "tag": "internal",
        },
        "image_rotator": {
            "type": "Retarder",
            "properties": {"phi": 2 * np.pi * 0.3, "theta": 0},
            "tag": "internal",
        },
        "flc": {
            "type": "Retarder",
            "properties": {"phi": 2 * np.pi * 0.25, "theta": 0},
            "tag": "internal",
        },
        "wollaston": {
            "type": "WollastonPrism",
            "properties": {"beam": "o"},
            "tag": "internal",
        },
    },
    "order": [
        "parang_rot", "m3", "alt_rot", "hwp",
        "image_rotator", "flc", "wollaston"
    ]
}

# Fixed parameters for the original function
fixed_params = (0.25, 0.05, 5, 0.5, 10, 0.3, 5, 0.1, 0.03, 15, 0.25, 30, 1.0, 0, 30)

# Inputs for comparison
theta_pol = 45
HWP_angs = [0, 22.5, 45, 67.5]
IMR_angs = [0, 30, 60]

# Compare the models
instrument_mm.compare_internal_calibration(
    theta_pol, system_dict, fixed_params, HWP_angs, IMR_angs
)


TypeError: compare_internal_calibration.<locals>.original_model() takes 4 positional arguments but 21 were given

In [3]:
NFIRAOS = cmm.ArbitraryMatrix(name = "NFIRAOS")

NameError: name 'cmm' is not defined